// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsje1qAwvgeg3AzvJfFcP-4BVBf8oOyvU',
    appId: '1:209248706077:web:2ed35449b657ba3536b0f4',
    messagingSenderId: '209248706077',
    projectId: 'cobalt-academy-376006',
    authDomain: 'cobalt-academy-376006.firebaseapp.com',
    storageBucket: 'cobalt-academy-376006.appspot.com',
    measurementId: 'G-K8P1EPDCP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgU4Tv123gsDo6DlwrtSFGpX5Y2-auwEU',
    appId: '1:209248706077:android:98d0b62c1ce32efa36b0f4',
    messagingSenderId: '209248706077',
    projectId: 'cobalt-academy-376006',
    storageBucket: 'cobalt-academy-376006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG3Uj5rebk02OPj_0OW51tpeiXtmkRygE',
    appId: '1:209248706077:ios:0a80c86da75cd41136b0f4',
    messagingSenderId: '209248706077',
    projectId: 'cobalt-academy-376006',
    storageBucket: 'cobalt-academy-376006.appspot.com',
    iosClientId: '209248706077-sfqr7h051qd6di0us7aaa82kh3qksc4g.apps.googleusercontent.com',
    iosBundleId: 'ai.plaito.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG3Uj5rebk02OPj_0OW51tpeiXtmkRygE',
    appId: '1:209248706077:ios:0684fcb019934c8036b0f4',
    messagingSenderId: '209248706077',
    projectId: 'cobalt-academy-376006',
    storageBucket: 'cobalt-academy-376006.appspot.com',
    iosClientId: '209248706077-2r4j3t7nse3shb544kqh37trcocctb82.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiTutorFlutter',
  );
}
